//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EF_DatabaseFirst.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SinhVien
    {
        public int SinhVienID { get; set; }
        public string TenSinhVien { get; set; }
        public Nullable<int> Tuoi { get; set; }
        public Nullable<int> LopID { get; set; }
    
        public virtual Lop Lop { get; set; }
    }
}
